### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by TheSpartaPT** [FrazzIe/NativeUILua#9]
everytime you open a NativeUI menu the memory usage for that script gets a little higher each time

this is most noticeable with the EasyAdmin resource you just need to open it and close it as many times as you want while having the F8 console command "resmon 1" activated to check it

i know the issue comes from here because i also have some custom NativeUI menus and the behaviour is similar, doesn't get nearly as much memory usage as EasyAdmin but still happens

**Comment by Blumlaut** [comment]
this might've been more appropriate as an issue over at EasyAdmin, but i believe this is caused by EasyAdmin re-creating the UI every time you open it, although i'm sure i also deleted the old one...

**Comment by TheSpartaPT** [comment]
still i have 3 more NativeUI menus that do the same thing but not nearly as much as yours,
they were based on your EasyAdmin now that i think about it but yeah

**Comment by FrazzIe** [comment]
I have a full GTA:O Character Creator with over 70 menus and i myself see 120mb ram usage, i'm trying to work on it but i'm not really getting anywhere, and i'm not even recreating menus.

**Comment by Firecul** [comment]
From my own testing when I found the resmon my own menu (not based on NativeUI lua or otherwise) gets up to about 17MB but then the fivem garbage collection takes it back down to it's normal 5.4MB. The ExampleMenu in this repo uses 3.7MB normally but it counts up while open to 9.7MB then resets so I think that's not too bad.

**Comment by FrazzIe** [comment]
I can't find the issue at all, i'm hoping someone can save me, i'm dying here.

**Comment by TheSpartaPT** [comment]
![imagem](https://user-images.githubusercontent.com/8343238/44086443-7483ba00-9fb4-11e8-8835-c15b1f6e47d2.png)

this is EasyAdmin after spamming the open key (which opens and closes acordingly) after your new update @Bluethefurry 

notice the characters on the menu got bold after me spamming so i think me closing the menu doesn't actually delete it, so when you press the open key again you're showing all the menus you opened and closed before plus a new one, so those characters getting bold is actually an overlap of characters or previous menus i think

and this is one of my other NativeUI menus i probably spammed it more than EasyAdmin
![imagem](https://user-images.githubusercontent.com/8343238/44087171-cd270976-9fb6-11e8-8f10-f7d6f3d35209.png)

see the memory usage doesn't get nearly as high as EasyAdmin but still grows each time i open it and close it, and the characters didn't get "bold"

**Comment by Blumlaut** [comment]
i am aware, i already pushed a fix for it which will be integrated into the next release ( see https://github.com/Bluethefurry/EasyAdmin/commit/d9fedf42f09be630bd78de356a7a490571037622 note: not stable yet )

**Comment by TheSpartaPT** [comment]
yeah i tested it with your new version, still happens @Bluethefurry

**Comment by Blumlaut** [comment]
just noticed that too, local test env works fine but with other player it seems to leak massively still, idk.

**Comment by TheSpartaPT** [comment]
maybe it has something to do with your player management submenu ? just a shot in the dark, since it's one of the things that changes when you have players online

**Comment by Blumlaut** [comment]
oddly enough, MenuPool.Clear() should get rid of all that, so i don't understand why that still happens

**Comment by TheSpartaPT** [comment]
can confirm that the latest @Bluethefurry update fixed it, now it stays at 8 MB used even if i spam it.

you can close this and label it as fixed
